# Numpy Introduction

In [2]:
# install Numpy
# pip install numpy

In [3]:
import numpy as np

In [4]:
a= np.arange(6)
print(a)
a.shape

[0 1 2 3 4 5]


(6,)

In [5]:
a2 = a[np.newaxis,:]
print(a2)
a2.shape

[[0 1 2 3 4 5]]


(1, 6)

In [6]:
a2 = a[:,np.newaxis]
print(a2)
a2.shape

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]


(6, 1)

In [7]:
a3 = a2[np.newaxis,:]
print(a3)
a3.shape

[[[0]
  [1]
  [2]
  [3]
  [4]
  [5]]]


(1, 6, 1)

# why do we Have  1D ,2D, 3D arrays  and where we need them in data Science

## Creating arrays in numpy

In [16]:
a = np.array([1,2,3,4,5,6,])
b = np.array([(7,8,9,10,11,12),(13,14,15,16,17,18)])
a.shape
b.shape
print(a)
print(b)
a.dtype
b.dtype  # data type of array elements

[1 2 3 4 5 6]
[[ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]


dtype('int32')

In [22]:
type(a)  # type of array

numpy.ndarray

# Initialize arrays

In [17]:
zeros = np.zeros((2,4)) # Rows, Columns
zeros
zeros.dtype

dtype('float64')

In [18]:
ones= np.ones((4,4))
ones
ones.dtype

dtype('float64')

In [20]:
full = np.full((2,5),7.5)
full
full.dtype

dtype('float64')

In [21]:
identity = np.eye(5) # creating an identity matrix
identity
identity.dtype

dtype('float64')

# Array Attributes

In [23]:
a.shape  # shape of ana array

(6,)

In [24]:
len(a)  # length of an Array

6

In [26]:
# give the dimension of the array

a.ndim
b.ndim

2

In [28]:
# size(number) of ana array
a.size
b.size

12

# Basic Operations

In [30]:
a

array([1, 2, 3, 4, 5, 6])

In [31]:
b

array([[ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18]])

In [32]:
g = b - a  # substraction
g

array([[ 6,  6,  6,  6,  6,  6],
       [12, 12, 12, 12, 12, 12]])

In [33]:
# addition

h = a + b
h

array([[ 8, 10, 12, 14, 16, 18],
       [14, 16, 18, 20, 22, 24]])

In [35]:
h1 = np.add(a,b)
h1

array([[ 8, 10, 12, 14, 16, 18],
       [14, 16, 18, 20, 22, 24]])

In [37]:
# devision

j = a/b
j

array([[0.14285714, 0.25      , 0.33333333, 0.4       , 0.45454545,
        0.5       ],
       [0.07692308, 0.14285714, 0.2       , 0.25      , 0.29411765,
        0.33333333]])

In [38]:
# multiplication
i = a*b
i

array([[  7,  16,  27,  40,  55,  72],
       [ 13,  28,  45,  64,  85, 108]])

In [41]:
# square of each element
k = a ** 3
k

array([  1,   8,  27,  64, 125, 216], dtype=int32)