# Numpy (Part - 2)

In [27]:
import numpy as np

In [28]:
# Create an empty array with 2 elements
empty  = np.empty((3,4)) 
print(empty)
print("-----------")
print(empty[1])

[[2.12199579e-314 6.36598737e-314 1.06099790e-313 1.48539705e-313]
 [2.12199579e-314 6.36598737e-314 1.06099790e-313 1.48539705e-313]
 [2.12199579e-314 6.36598737e-314 1.06099790e-313 1.48539705e-313]]
-----------
[2.12199579e-314 6.36598737e-314 1.06099790e-313 1.48539705e-313]


In [29]:
np.arange(10)  # range function

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
# Array of even numbers

even = np.arange(0, 23,2)
even

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

In [31]:
# Array of odd numbers
odd = np.arange(1,23,2)
odd

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21])

In [32]:
# specific difference between numbers
diff = np.arange(0,23,0.515)
diff

array([ 0.   ,  0.515,  1.03 ,  1.545,  2.06 ,  2.575,  3.09 ,  3.605,
        4.12 ,  4.635,  5.15 ,  5.665,  6.18 ,  6.695,  7.21 ,  7.725,
        8.24 ,  8.755,  9.27 ,  9.785, 10.3  , 10.815, 11.33 , 11.845,
       12.36 , 12.875, 13.39 , 13.905, 14.42 , 14.935, 15.45 , 15.965,
       16.48 , 16.995, 17.51 , 18.025, 18.54 , 19.055, 19.57 , 20.085,
       20.6  , 21.115, 21.63 , 22.145, 22.66 ])

In [33]:
# lin space array with a specific interval of the value

lin = np.linspace(0, 10, num=15)
lin


array([ 0.        ,  0.71428571,  1.42857143,  2.14285714,  2.85714286,
        3.57142857,  4.28571429,  5.        ,  5.71428571,  6.42857143,
        7.14285714,  7.85714286,  8.57142857,  9.28571429, 10.        ])

In [34]:
# define the datatype of ana array
x = np.ones(2, dtype=np.float64)
x

array([1., 1.])

In [35]:
# define the datatype of ana array
x = np.arange(0,22.6,1.5, dtype=np.int64)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
      dtype=int64)

# Assignment - What is the diffrence between int32, int64, or float16,32,64. inka matlab kya hai ?  why do we use one and not the other one?

In [36]:
# sorting of an array
arr  = np.array([2,1,5,3,7,4,6,8])
arr
arr = np.sort(arr)
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [37]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])

In [38]:
# concatenete the array
c = np.concatenate((a,b))
c

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [39]:
x = np.array([[1,2],[3,4]]) # 2x2 array
y = np.array([[5,6]]) # 1x2 array

In [40]:
x.size


4

In [41]:
y.size

2

# Concatenate 2D arrays

In [42]:
# concatenate 2D array
z = np.concatenate((x,y),axis=0)
z

array([[1, 2],
       [3, 4],
       [5, 6]])

In [43]:
w  = np.array([[5,1],[7,1]])
w

array([[5, 1],
       [7, 1]])

In [44]:
z1 = np.concatenate((w,x),axis=1)
z1

array([[5, 1, 1, 2],
       [7, 1, 3, 4]])

In [45]:
z1.ndim

2

# 3D Arrays

In [46]:
# Create a 3D array
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])
# Print the shape of the 3d array
print(array_example.shape)
array_example.ndim
array_example.size


(3, 2, 4)


24

In [47]:
array_example.dtype
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [48]:
# Create 3D array of size (3,1,4)
arr = np.array([[[0,1,2,3]],
                [[4,5,6,7]],
                [[8,9,10,11]]])
arr.ndim
arr.shape



(3, 1, 4)

In [52]:
# reshape the array
a = arr.reshape(6,2)
a.shape

(6, 2)

In [54]:
arr

array([[[ 0,  1,  2,  3]],

       [[ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11]]])

In [53]:
a

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [60]:
a.reshape(2,2,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [61]:
# create a 1D array
a  =np.array([1,2,3,4,5,6,7,8])
a.shape

(8,)

In [68]:
# convert that into 2D array
b = a[np.newaxis,:].shape
b



(1, 8)

In [70]:
c = a[:,np.newaxis]
c.shape

(8, 1)

# Indexing and Slicing

In [71]:
a  =np.array([1,2,3,4,5,6,7,8])
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [75]:
a[3:7]

array([4, 5, 6, 7])

In [77]:
b = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

<>:1: SyntaxWarning: 'int' object is not subscriptable; perhaps you missed a comma?
<>:1: SyntaxWarning: 'int' object is not subscriptable; perhaps you missed a comma?
C:\Users\Vikas\AppData\Local\Temp\ipykernel_2968\2240522599.py:1: SyntaxWarning: 'int' object is not subscriptable; perhaps you missed a comma?
  b[2[3]]
C:\Users\Vikas\AppData\Local\Temp\ipykernel_2968\2240522599.py:1: SyntaxWarning: 'int' object is not subscriptable; perhaps you missed a comma?
  b[2[3]]
C:\Users\Vikas\AppData\Local\Temp\ipykernel_2968\2240522599.py:1: SyntaxWarning: 'int' object is not subscriptable; perhaps you missed a comma?
  b[2[3]]
C:\Users\Vikas\AppData\Local\Temp\ipykernel_2968\2240522599.py:1: SyntaxWarning: 'int' object is not subscriptable; perhaps you missed a comma?
  b[2[3]]


TypeError: 'int' object is not subscriptable

In [80]:
b[2]

array([ 9, 10, 11, 12])

In [85]:
# filter odd numbers
b[b<10]
b[b%2==0]

array([ 2,  4,  6,  8, 10, 12])

In [86]:
# use two comditions
b[(b>2)&(b<11)]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [87]:
b[(b>2)|(b<11)]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])